import { esc as e, safeURL, dateLabel, stages, stageStyle } from './lib.mjs';
const icons={
 arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',external:'<path d="M7 17 17 7M7 7h10v10"/>',down:'<path d="M12 5v14m-6-6 6 6 6-6"/>',up:'<path d="M12 19V5m-6 6 6-6 6 6"/>',
 book:'<path d="M3 4h6a4 4 0 0 1 3 2 4 4 0 0 1 3-2h6v15h-6a4 4 0 0 0-3 2 4 4 0 0 0-3-2H3zM12 6v15"/>',
 video:'<rect x="3" y="5" width="18" height="14" rx="4"/><path d="m10 9 5 3-5 3z"/>',play:'<path d="m8 5 11 7-11 7z"/>',
 globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c5 5 5 13 0 18-5-5-5-13 0-18Z"/>',
 grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
 toolbox:'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V4h8v3M3 12h18m-13-2v4m8-4v4"/>',
 trend:'<path d="m3 17 6-6 4 3 8-10M14 4h7v7"/>',status:'<path d="M5 20V9m7 11V4m7 16v-7M3 9h4m3-5h4m3 9h4"/>',
 wallet:'<path d="M20 7H5a2 2 0 0 1 0-4h13v4M3 5v14a2 2 0 0 0 2 2h15V7m0 6h-5v4h5"/>',
 info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7v.1"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',menu:'<path d="M4 7h16M4 12h16M4 17h16"/>',
 chat:'<path d="M21 11a8 8 0 0 1-8 8H8l-5 3 1-6a8 8 0 1 1 17-5Z"/><path d="M8 11h.1M12 11h.1M16 11h.1"/>',
 copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5ZM20 2v4m-2-2h4"/>',
 shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6ZM8 12l3 3 5-6"/>',leaf:'<path d="M20 3C10 3 3 6 4 13c1 7 13 9 16-10ZM3 21 15 9"/>'
};
export const icon=(name,extra='')=>`<svg class="icon ${e(extra)}" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.arrow}</svg>`;
const ext=(url,text,cls='text-link',ic='external')=>`<a class="${cls}" href="${e(safeURL(url))}" target="_blank" rel="noopener noreferrer">${text}${icon(ic)}</a>`;
const go=(page,text,cls='text-link',ic='arrow')=>`<a class="${cls}" href="${page}.html">${text}${icon(ic)}</a>`;
export const nav=[['index','首页'],['articles','文章'],['videos','视频'],['market','市场看板'],['tools','工具箱'],['about','关于']];
export function header(site,page){return `<a class="skip-link" href="#main">跳到主要内容</a><header class="site-header"><div class="container header-inner"><a class="brand" href="index.html" aria-label="${e(site.name)}首页"><span class="brand-mark">赵</span><span class="brand-word"><strong>${e(site.name)}</strong><small>MARKET NOTES</small></span></a><nav class="desktop-nav" aria-label="主要导航">${nav.map(([p,t])=>`<a href="${p}.html" ${page===p?'class="active" aria-current="page"':''}>${t}</a>`).join('')}</nav><button class="header-follow" data-follow>${icon('chat')}关注老赵</button><button class="menu-button" aria-label="打开导航菜单" aria-controls="mobileNav" aria-expanded="false">${icon('menu')}</button></div><nav class="mobile-nav" id="mobileNav" aria-label="手机导航" hidden>${nav.map(([p,t])=>`<a href="${p}.html" ${page===p?'class="active" aria-current="page"':''}>${t}</a>`).join('')}</nav></header>`;}
export function footer(site){return `<footer class="site-footer"><div class="container"><div class="footer-top"><div><strong>${e(site.name)}</strong><span> &nbsp;© 2026</span>${site.previewMode?'<span class="preview-mode-tag">设计预览 v1.0</span>':''}</div><div class="footer-links"><button data-follow>公众号</button><a href="${e(site.youtubeUrl)}" target="_blank" rel="noopener noreferrer">YouTube</a><a href="about.html">关于本站</a></div></div><p class="footer-note">数据来自市场公开信息，由老赵市场工具箱整理。阶段信息仅用于辅助观察，不代表未来表现，不构成投资建议。${site.previewMode?'本版本含明确标注的内容样例；市场数据为带日期的公开历史快照。':''}<br>把决策交给系统，把时间留给自己。</p></div></footer><button class="back-to-top" aria-label="返回页面顶部" hidden>${icon('up')}</button>`;}
const sectionHead=(n,kicker,title,desc,link)=>`<div class="section-head"><div><span class="section-kicker"><b>${n}</b>${kicker}</span><h2>${title}</h2>${desc?`<p class="section-description">${desc}</p>`:''}</div>${link||''}</div>`;
function articleMeta(a){return `<div class="content-meta"><span class="category">${e(a.category)}</span><span>${a.status==='published'?dateLabel(a.date):'公众号选题'}</span>${a.status!=='published'?'<span class="sample-tag">样例</span>':''}</div>`;}
function articleFoot(a){return `<div class="article-foot"><span>${a.status==='published'?'来自「老赵市场笔记」':'原文链接待接入'}</span>${a.status==='published'?ext(a.url,'阅读原文','text-link'): `<button class="text-link" data-article="${e(a.id)}">查看简介${icon('arrow')}</button>`}</div>`;}
function articleCover(a){const content={toolkit:['LZ / MARKET TOOLKIT','把方法做成工具','官网 2.0 · 设计封面'],coding:['AI / CODING','AI\nCoding','从想法到工具'],stage:['LZ / 4STAGE','看全局\n懂周期','春 · 夏 · 秋 · 冬'],market:['GLOBAL / VIEW','市场的四季','全球市场观察'],method:['METHOD / NOTES','跟随趋势\n保持一致','方法 · 节奏 · 边界'],backtest:['LZ / RESEARCH','让数据\n检验方法','历史回测研究']}[a.theme]||['MARKET NOTES',a.title,'老赵市场笔记'];return `<div class="cover cover-${e(a.theme)}" aria-hidden="true"><span class="cover-kicker">${content[0]}</span><div class="cover-main">${content[1]}${a.theme==='toolkit'?'<div class="toolkit-line"><i></i><i></i><i></i><i></i></div>':''}</div><div class="cover-bottom"><span>${content[2]}</span><span>${a.theme==='coding'?'&lt;/&gt;':'LZ'}</span></div></div>`;}
function articleCard(a,compact=false,filter=false){return `<article class="${compact?'article-compact':'featured-article'}" ${filter?`data-filter-item data-category="${e(a.category)}" data-search="${e(a.title+' '+a.summary+' '+a.tags.join(' '))}" data-date="${e(a.date||a.draftDate||'')}"`:''}>${articleCover(a)}<div class="${compact?'':'article-body'}">${articleMeta(a)}<h3>${e(a.title)}</h3><p>${e(a.summary)}</p>${articleFoot(a)}</div></article>`;}
function sampleNotice(items,type){return items.some(x=>x.status!=='published')?`<p class="sample-notice">${icon('info')}${type==='articles'?'选题版式预览：原文链接与发布日期待核验，未模拟公众号抓取。':'视频版式预览：封面为设计样例，真实视频链接待关联。'}</p>`:'';}
function videoCover(v){const valid=safeURL(v.thumbnail,['i.ytimg.com','img.youtube.com']);return valid?`<div class="cover video-cover" style="padding:0"><img src="${e(valid)}" alt="${e(v.title)}" loading="lazy" referrerpolicy="no-referrer" style="width:100%;height:100%;object-fit:cover;position:absolute;inset:0"><span class="play-symbol">${icon('play')}</span></div>`:`<div class="cover video-cover cover-${e(v.theme||'cross')}"><span class="cover-kicker">LZ / MARKET WATCH</span><span class="sample-cover">${v.status==='published'?'文字封面':'封面样例'}</span><div class="cover-main">${e(v.coverTitle||v.title)}</div><span class="cover-bottom">老赵市场观察</span><span class="play-symbol">${icon(v.status==='published'?'play':'external')}</span></div>`;}
function videoCard(v,site,filter=false){return `<article class="video-card" ${filter?`data-filter-item data-category="${e(v.category)}" data-search="${e(v.title+' '+v.summary)}" data-date="${e(v.publishedAt||'')}"`:''}><button class="video-cover-button" data-video="${e(v.id)}" aria-label="${v.status==='published'?'播放':'查看待关联视频主题'}：${e(v.title)}">${videoCover(v)}</button><div class="content-meta"><span class="category">${e(v.category)}</span><span>${v.publishedAt?dateLabel(v.publishedAt):'视频主题样例'}</span></div><h3>${e(v.title)}</h3><p>${e(v.summary)}</p><div class="video-footer"><span>${v.status==='published'?'YouTube · 老赵市场观察':'待关联真实视频'}</span><a href="${e(v.status==='published'?v.url:site.youtubeUrl)}" target="_blank" rel="noopener noreferrer">${v.status==='published'?'YouTube 观看':'前往频道'} ↗</a></div></article>`;}
export function marketCard(m,full=false,filter=false){return `<button class="market-card" style="${stageStyle(m.stage)}" data-market="${e(m.code)}" data-code="${e(m.code)}" ${filter?`data-filter-item data-region="${e(m.region)}" data-stage="${e(m.stage)}" data-search="${e(m.name+' '+m.symbol)}"`:''} aria-label="${e(m.name)}，${stages[m.stage].name} ${e(m.stage)}，持续 ${m.weeks} 周，查看详细信息"><div class="market-top"><span class="market-symbol">${e(m.symbol||m.code)}</span><span class="market-stage">${stages[m.stage].name} · ${e(m.stage)}</span></div><h3>${e(m.name)}</h3><div class="market-bottom"><span><strong>${m.weeks}</strong> 周<span style="opacity:.7"> · 阶段持续</span></span><span class="substage">${e(m.subStage)}</span></div>${full?`<div class="market-detail-dates">阶段口径 ${dateLabel(m.stageAsOf)}</div>`:''}</button>`;}
function counts(m){return `<div class="stage-counts">${Object.entries(stages).map(([k,v])=>`<span style="${stageStyle(k)}"><i></i>${v.short} ${k} <b>${m.interpretation.stageCounts[k]}</b></span>`).join('')}</div>`;}
const snapshotLabel=m=>`<span class="snapshot-label">${icon('clock')}${m.syncedAt?'公开数据快照':'内置历史快照'} · ${dateLabel(m.generatedAt)}</span>`;
const dataNote=(m)=>`<p class="data-note">${icon('info')}<span>来源：LZ-4Stage Map 公开快照。按已完成周线分析；生成时间不等于阶段确认日期。仅代表 ${m.markets.length} 个精选资产，不代表全市场或配置建议。</span></p>`;
const tools=[
 {id:'map',name:'LZ-4Stage Map',tag:'Map 找方向',desc:'先看全球市场处于什么季节，再决定关注哪些方向。',icon:'globe',color:'#3676d7',soft:'#eaf2ff',label:'查看阶段地图'},
 {id:'stage',name:'LZ-4Stage',tag:'4Stage 判趋势',desc:'用四季框架理解趋势生命周期，识别阶段与位置。',icon:'grid',color:'#348367',soft:'#ebf5ef',label:'了解四季框架'},
 {id:'status',name:'LZ-Status',tag:'Status 看状态',desc:'结合综合评分与状态变化，辅助观察当前市场节奏。',icon:'status',color:'#ad7a2f',soft:'#fbf4e7',label:'了解状态系统'},
 {id:'dca',name:'LZ-DCA',tag:'DCA 管资金',desc:'关注定投温度与资金分配，让长期投入更有章法。',icon:'wallet',color:'#3067c5',soft:'#ecf2fd',label:'了解趋势定投'}
];
function toolCards(site){return `<div class="toolkit-grid">${tools.map((t,i)=>`<article class="tool-card" style="--tool-color:${t.color};--tool-soft:${t.soft}"><div class="tool-top"><div class="tool-icon">${icon(t.icon)}</div><span class="tool-number">0${i+1}</span></div><h3>${t.name}</h3><h4>${t.tag}</h4><p>${t.desc}</p>${ext(t.id==='map'?site.mapUrl:site.toolkitUrl+'#framework',t.label,'','external')}</article>`).join('')}</div>`;}
function aboutStrip(){return `<section class="about-strip" id="about"><div class="container about-strip-inner"><span class="about-emblem" aria-hidden="true">赵</span><div><h2>我是老赵。很高兴在这里遇见你。</h2><p>把市场观察写成笔记，把投资方法做成工具。<br>分享思考与实践，也认真说明它们的边界。</p></div>${go('about','认识老赵','button dark-line')}</div></section>`;}
function hero(site){return `<section class="hero"><div class="container"><div class="hero-layout"><div class="hero-copy"><p class="eyebrow">市场观察 · 投资方法 · AI 实践</p><h1>看清市场的四季，<br><em>记录投资的思考。</em></h1><p class="hero-lead">你好，我是老赵。一名技术型投资研究者。<br>在这里，分享市场观察、系统工具，以及 AI 带来的新可能。</p><div class="hero-actions"><a class="button primary" href="#articles">阅读最新笔记${icon('arrow')}</a>${ext(site.mapUrl,'查看市场地图','button secondary')}</div><div class="author-line"><span class="author-dot">赵</span><b>老赵</b><span>／</span><span>把方法做成工具，把思考留下来</span></div></div><div class="hero-visual"><div class="cycle-paper"><div class="paper-top"><b>LZ / FIELD NOTES</b><span class="mini-cross">＋</span></div><h2>市场有周期，<br><span>投资有节奏。</span></h2><svg class="cycle-chart" viewBox="0 0 440 140" role="img" aria-label="四季周期概念示意，非历史行情"><path d="M10 121 C35 124 50 118 76 118 S100 104 114 96" stroke="#4886db" stroke-width="3" fill="none"/><path d="M114 96 C148 86 161 63 186 31 S216 10 240 12" stroke="#278667" stroke-width="3" fill="none"/><path d="M240 12 C267 2 289 13 310 28 S333 36 344 43" stroke="#bf873e" stroke-width="3" fill="none"/><path d="M344 43 C368 57 371 83 394 104 S420 119 432 117" stroke="#a9667a" stroke-width="3" fill="none"/><circle cx="75" cy="118" r="5" fill="#fff" stroke="#4886db" stroke-width="2"/><circle cx="188" cy="29" r="5" fill="#fff" stroke="#278667" stroke-width="2"/><circle cx="308" cy="27" r="5" fill="#fff" stroke="#bf873e" stroke-width="2"/><circle cx="409" cy="113" r="5" fill="#fff" stroke="#a9667a" stroke-width="2"/></svg><div class="cycle-legend">${Object.entries(stages).map(([k,s])=>`<div class="cycle-season" style="${stageStyle(k)}"><strong>${s.short} <small>${k}</small></strong><span>${{S1:'SPRING',S2:'SUMMER',S3:'AUTUMN',S4:'WINTER'}[k]}</span></div>`).join('')}</div><div class="paper-bottom"><span>四季框架示意 · 非历史行情</span><span>OBSERVE. THINK. REPEAT.</span></div></div></div></div><div class="hero-bridge"><span>一个入口，连接内容与工具。</span><div class="bridge-links"><a href="articles.html">${icon('book')}<span>公众号笔记</span></a><a href="videos.html">${icon('video')}<span>视频与案例</span></a><a href="market.html">${icon('globe')}<span>市场阶段</span></a><a href="tools.html">${icon('toolbox')}<span>系统工具</span></a></div></div></div></section>`;}
export function home({site,articles,videos,market}){const selected=site.homeMarkets.map(c=>market.markets.find(m=>m.code===c)).filter(Boolean);const aa=articles.items.slice(0,3);return `${hero(site)}<section class="section market-section" id="market"><div class="container">${sectionHead('01','MARKET SNAPSHOT','市场走到了哪个季节？','用同一套四季语言，观察不同市场的节奏。',go('market','完整看板'))}<div class="snapshot-row">${snapshotLabel(market)}${counts(market)}</div><div class="market-grid">${selected.map(m=>marketCard(m)).join('')}</div><div class="market-interpretation"><div class="interpretation-label">${icon('spark')}全球阶段解读</div><p>精选样本中，夏季资产为 ${market.interpretation.stageCounts.S2}/${market.markets.length}；同时仍有 ${market.interpretation.stageCounts.S4} 个资产处于冬季。<br>${Object.values(market.interpretation.stageCounts).filter(n=>n>0).length>1?'市场没有走在同一个季节里，':'本组样本处于同一季节，'}阶段含义需要结合资产类别理解。</p>${go('market','查看解读')}</div>${dataNote(market)}</div></section><section class="section muted-section" id="articles"><div class="container">${sectionHead('02','LATEST NOTES','最近写下的思考','来自公众号「老赵市场笔记」。',go('articles','全部文章'))}${sampleNotice(articles.items,'articles')}<div class="article-home-grid">${aa[0]?articleCard(aa[0]):''}<div class="article-side">${aa.slice(1).map(a=>articleCard(a,true)).join('')}</div></div><div class="article-extra"><span>不只看行情，也分享方法、工具和 AI 实践。</span><button data-follow>关注公众号 ↗</button></div></div></section><section class="section" id="videos"><div class="container">${sectionHead('03','WATCH & LEARN','用视频，把方法讲清楚','市场观察、系统教程与案例分析。',go('videos','全部视频'))}${sampleNotice(videos.items,'videos')}<div class="video-grid">${videos.items.slice(0,3).map(v=>videoCard(v,site)).join('')}</div><p class="video-caption">${icon('video')}原视频发布于 YouTube · 老赵市场观察。网站整理内容，不托管视频文件。</p></div></section><section class="section toolkit-section" id="toolkit"><div class="container">${sectionHead('04','MARKET TOOLKIT','把方法，做成真正能用的工具。','从看清全局，到管理资金，各自解决一个明确的问题。',ext(site.toolkitUrl,'工具箱官网'))}${toolCards(site)}<p class="toolkit-summary">Map 找方向 &nbsp;→&nbsp; 4Stage 判趋势 &nbsp;→&nbsp; Status 看状态 &nbsp;→&nbsp; DCA 管资金</p></div></section>${aboutStrip()}`;}
function intro(kicker,title,desc,extra='',right=''){return `<section class="page-intro"><div class="container"><div class="breadcrumb"><a href="index.html">首页</a> &nbsp; / &nbsp; ${title}</div><p class="eyebrow">${kicker}</p><h1>${title}</h1><p class="lead">${desc}</p>${extra||right?`<div class="page-intro-bottom">${extra}${right}</div>`:''}</div></section>`;}
const chip=(label,active=false,group='category')=>`<button class="filter-chip${active?' active':''}" data-filter="${e(label)}" data-group="${group}" aria-pressed="${active}">${e(label)}</button>`;
const search=(placeholder)=>`<label class="search-box">${icon('search')}<input type="search" data-search-input placeholder="${placeholder}" aria-label="${placeholder}" autocomplete="off"></label>`;
const empty=()=>`<div class="empty-state" data-empty hidden>${icon('search')}<h3>暂时没有找到相关内容</h3><p>换一个关键词，或清除筛选再看看。</p><button class="button secondary" data-reset>清除筛选</button></div>`;
export function articlePage({site,articles}){const hasSamples=articles.items.some(x=>x.status!=='published');return `${intro('ARTICLES / 老赵市场笔记','文章与思考','把日常的观察写下来，把反复验证的方法留下来。<br>关于市场，也关于工具、技术和个人实践。','<span>原文发布于公众号 · 老赵市场笔记</span>','<button class="text-link" style="border:0;background:none;padding:0" data-follow>关注公众号 '+icon('external')+'</button>')}<section class="content-section"><div class="container" data-filter-root="articles"><div class="filters"><div class="filter-chips" aria-label="文章分类">${['全部','市场观察','投资方法','工具使用','AI 实践'].map((x,i)=>chip(x,i===0)).join('')}</div>${search('搜索文章、主题或关键词')}</div><div class="results-meta"><span data-results-count aria-live="polite">共 ${articles.items.length} 篇内容</span><label>排序 <select data-sort aria-label="文章排序"><option value="newest">最近收录</option><option value="oldest">较早收录</option></select></label></div>${sampleNotice(articles.items,'articles')}<div class="articles-grid" data-items-container>${articles.items.map(a=>articleCard(a,false,true)).join('')}</div>${empty()}<div class="boundary"><h3>内容来自哪里？</h3><p>${hasSamples?'这里是文章目录。正式内容链接至「老赵市场笔记」公众号原文，不冒充全文转载。标注“样例”的内容只用于展示版式；接入原文后会显示经过核实的发布日期与“阅读原文”按钮。':'这里是「老赵市场笔记」的文章目录。标题、发布日期与页面摘要已经核验；点击“阅读原文”将前往公众号页面。本站不复制公众号正文。'}</p></div></div></section>`;}
export function videoPage({site,videos}){return `${intro('VIDEOS / 老赵市场观察','视频与案例','把抽象的方法放回图表与案例中，一步一步讲清楚。<br>所有原视频都发布在 YouTube。','<span>频道 · @lzmarketwatch</span>',ext(site.youtubeUrl,'访问 YouTube 频道'))}<section class="content-section page-videos"><div class="container" data-filter-root="videos"><div class="filters"><div class="filter-chips" aria-label="视频分类">${['全部','市场观察','系统教程'].map((x,i)=>chip(x,i===0)).join('')}</div>${search('搜索视频主题')}</div><div class="results-meta"><span data-results-count aria-live="polite">共 ${videos.items.length} 条内容</span><span>${videos.lastSyncedAt?'目录同步 '+dateLabel(videos.lastSyncedAt):'真实视频目录待接入'}</span></div>${sampleNotice(videos.items,'videos')}<div class="video-grid" data-items-container>${videos.items.map(v=>videoCard(v,site,true)).join('')}</div>${empty()}<div class="boundary"><h3>关于观看</h3><p>正式视频只在你点击播放后加载 YouTube 播放器。站内嵌入不改变视频来源，也不保证所有网络都能播放；标题、介绍和文章内容不依赖播放器加载。未关联的视频主题不会生成假的播放地址或观看数据。</p></div></div></section>`;}
export function marketPage({site,market}){const c=market.interpretation.stageCounts;const ranked=Object.entries(c).sort((a,b)=>b[1]-a[1]);const different=Object.values(c).filter(v=>v>0).length;const dominant=ranked[0][1]===ranked[1][1]?'多个季节并存':`${stages[ranked[0][0]].name}资产占比较高`;return `${intro('MARKETS / LZ-4STAGE MAP','全球市场阶段看板','看清位置，比急着下结论更重要。<br>用春夏秋冬的语言，理解各个市场所处的阶段。',snapshotLabel(market),ext(site.mapUrl,'打开完整 Map'))}<section class="content-section"><div class="container"><div class="market-dashboard-top"><div class="interpretation-panel"><p class="eyebrow">全球市场阶段解读</p><h2>${dominant}，<br>${different>1?'各市场节奏仍有分化。':'持续关注阶段变化。'}</h2><p>当前快照的 ${market.markets.length} 个样本中，${c.S2} 个处于夏季、${c.S4} 个处于冬季。阶段是观察位置，不是未来结果。</p></div><div class="structure-panel"><h3>精选资产 · 阶段分布</h3><p class="structure-total"><strong>${market.markets.length}</strong> 个公开样本</p><div class="structure-bar" aria-label="阶段分布">${Object.keys(stages).map(k=>`<span style="${stageStyle(k)};flex:${c[k]}" title="${stages[k].name} ${c[k]} 个"></span>`).join('')}</div>${counts(market)}</div></div><div data-filter-root="market"><div class="filters"><div class="filter-chips" aria-label="按阶段筛选">${['全部','春季 S1','夏季 S2','秋季 S3','冬季 S4'].map((x,i)=>chip(x,i===0,'stage')).join('')}</div><label><select class="filter-select" data-region aria-label="按市场类别筛选"><option value="全部">全部市场</option>${[...new Set(market.markets.map(m=>m.region))].map(r=>`<option>${e(r)}</option>`).join('')}</select></label></div><div class="results-meta"><span data-results-count aria-live="polite">共 ${market.markets.length} 个资产</span><span>点击卡片查看口径日期与观察状态</span></div><div class="market-grid" data-items-container>${market.markets.map(m=>marketCard(m,true,true)).join('')}</div>${empty()}</div>${dataNote(market)}<div class="insights-grid">${market.interpretation.insights.map(x=>`<article class="insight-card"><h3>${e(x.label)} · 来源快照原文</h3><p>${e(x.text)}</p></article>`).join('')}</div><div class="boundary"><h3>先理解口径，再理解阶段</h3><p>本页只展示 Map 已公开的全球样本，不包含会员数据或核心计算。阶段数量并非配置权重；持续周数不是趋势“进度百分比”。美国 10 年期国债收益率不等于债券价格，宏观资产与股票的阶段含义应分别理解。观察信号也不等于已确认的阶段变化。</p><p style="margin-top:10px">快照生成时间：${e(new Date(market.generatedAt).toISOString().replace('T',' ').slice(0,19))} UTC。各资产阶段口径日期见卡片；加密样本的确认日期使用周线起始日期口径，详情保留已完成周末日期。</p></div></div></section>`;}
export function toolsPage({site}){return `${intro('TOOLS / MARKET TOOLKIT','老赵市场工具箱','工具的意义，不是替你预测未来。<br>而是帮助你建立更清晰、更一致的观察与决策过程。','<span>个人站介绍产品，完整功能与版本说明以官网为准。</span>',ext(site.toolkitUrl,'访问工具箱官网'))}<section class="content-section"><div class="container"><div class="tools-page-cards">${toolCards(site)}</div><div class="tool-explain"><div><p class="eyebrow">ONE FRAMEWORK / FOUR QUESTIONS</p><h2>先看全局，再看资产。<br>先有框架，再做判断。</h2></div><p>Map 负责市场导航，4Stage 负责理解趋势，Status 负责观察状态，DCA 负责资金节奏。它们不是四个重复的信号，而是观察同一个市场的不同层次。<br><br>这个页面只做产品概览，不重复维护价格、会员权限或购买入口。详细说明请查看工具箱官网。</p></div><div class="boundary"><h3>工具有使用场景，也有边界</h3><p>适合市场观察、阶段识别与方法研究。阶段与评分可能滞后，历史回测不能代表未来，任何系统都无法消除风险。这里不提供收益保证、代客操作或个性化交易指令。</p></div></div></section>${aboutStrip()}`;}
export function aboutPage({site}){return `${intro('ABOUT / HELLO, I AM LAO ZHAO','关于老赵','研究市场，也研究如何更好地做判断。')}<div class="container"><section class="about-main"><div class="about-copy"><h2>把市场观察写成笔记，<br>把投资方法做成工具。</h2><p>你好，我是老赵，一名技术型投资研究者，也是「老赵市场工具箱」的主理人。我关注全球市场、趋势与风险，也持续尝试用 AI 把经验变成可以反复使用的工具。</p><p>这个网站是我在互联网上的一个固定入口。公众号里的文章、YouTube 上的视频、市场阶段地图，以及工具箱的介绍，都整理在这里。</p><div class="about-quote">把决策交给系统，<br>把时间留给自己。</div><p>我更愿意分享一个判断是怎么形成的、哪些条件可能让它失效，而不是给出一个听起来确定的答案。写作、研究和做工具，本质上都在做同一件事：让思考更清楚。</p><div class="values-grid"><article class="value-card"><span>01 / OBSERVE</span><h3>保持观察</h3><p>尊重市场的变化，不把一次判断当成永久结论。</p></article><article class="value-card"><span>02 / BUILD</span><h3>持续实践</h3><p>把经验变成方法，把方法做成可以使用的工具。</p></article><article class="value-card"><span>03 / RESPECT</span><h3>说明边界</h3><p>承认不确定性，区分事实、观点与阶段观察。</p></article></div></div><aside class="about-side"><div class="brand-mark">赵</div><h3>老赵</h3><p>技术型投资研究者<br>老赵市场工具箱主理人</p><button class="button primary" data-follow>${icon('chat')}关注老赵</button>${ext(site.youtubeUrl,'YouTube 频道','button secondary')}${ext(site.toolkitUrl,'老赵市场工具箱','button secondary')}</aside></section></div>`;}
export function dialogShell(){return `<dialog class="dialog" id="contentDialog" aria-labelledby="dialogTitle"><div class="dialog-header"><span id="dialogEyebrow">MARKET NOTES</span><button class="dialog-close" aria-label="关闭弹窗">${icon('close')}</button></div><div class="dialog-body" id="dialogContent"></div></dialog><div class="toast" role="status" aria-live="polite" hidden></div>`;}
export function pageHTML(page,data,body,{style='',js='',standalone=false}={}){const title=page==='index'?`${data.site.name}｜看清市场的四季，记录投资的思考。`:`${nav.find(([p])=>p===page)?.[1]}｜${data.site.name}`;const client=JSON.stringify(data).replaceAll('<','\\u003c');const pending=[];if(data.articles.items.some(x=>x.status!=='published'))pending.push('公众号原文');if(data.videos.items.some(x=>x.status!=='published'))pending.push('视频链接');return `<!doctype html>\n<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#142741"><meta name="description" content="${e(data.site.description)}">${data.site.previewMode?'<meta name="robots" content="noindex,nofollow">':''}<title>${title}</title><link rel="icon" href="data:image/svg+xml,${encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="13" fill="#102741"/><text x="32" y="44" fill="white" font-size="40" text-anchor="middle" font-family="sans-serif">赵</text></svg>')}">${data.site.baseUrl&&!standalone?`<link rel="canonical" href="${e(data.site.baseUrl.replace(/\/$/,'')+'/'+(page==='index'?'':page+'.html'))}">`:''}${style?`<style>${style}</style>`:'<link rel="stylesheet" href="assets/styles.css">'}</head><body data-page="${page}">${standalone?`<div class="preview-banner">独立浏览器预览 · 6 个页面均可切换${pending.length?' · '+pending.join('与')+'待核验':''}</div>`:''}${header(data.site,page)}<noscript><p class="no-js">当前浏览器未启用 JavaScript。文章与外部链接仍可阅读；筛选、弹窗与手机导航需要启用 JavaScript。</p><style>.mobile-nav[hidden]{display:block!important}</style></noscript><main id="main">${body}</main>${footer(data.site)}${dialogShell()}<script id="site-data" type="application/json">${client}</script>${js?`<script>${js}</script>`:'<script src="assets/site.js" defer></script>'}</body></html>`;}
export const renderers={index:home,articles:articlePage,videos:videoPage,market:marketPage,tools:toolsPage,about:aboutPage};
